# Generated by Django 3.1.7 on 2021-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='default_email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
