# Generated by Django 3.1.7 on 2021-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='Master', max_length=15)),
                ('package_type', models.CharField(choices=[('single (< 5mins)', 'single (< 5mins)'), ('ep (< 35mins)', 'ep (< 35mins)'), ('album / LP (> 35mins)', 'album / LP (> 35mins)')], default='single (< 5mins)', max_length=1026)),
                ('deliver_by', models.DateField()),
                ('stem_choices', models.CharField(choices=[('max 5 grouped stems', 'max 5 grouped stems'), ('Individual track stems', 'individual track stems')], default=['max 5 grouped stems'], max_length=1026)),
                ('revisions', models.CharField(choices=[('3', '3'), ('6', '6')], default=3, max_length=1026)),
                ('reference_link_type', models.CharField(blank=True, choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026)),
                ('reference_link', models.URLField(blank=True)),
                ('mix_extras', models.CharField(blank=True, choices=[('Drum Replacement', 'Drum Replacement'), ('Instrumental Version', 'Instruemntal Version'), ('Show Ready Version', 'Show Ready Version'), ('A Capella Version', 'A Capella Version')], default='', max_length=1026)),
                ('contact', models.EmailField(default='', max_length=254)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='Mix', max_length=15)),
                ('package_type', models.CharField(choices=[('single (< 5mins)', 'single (< 5mins)'), ('ep (< 35mins)', 'ep (< 35mins)'), ('album / LP (> 35mins)', 'album / LP (> 35mins)')], default='single (< 5mins)', max_length=1026)),
                ('deliver_by', models.DateField()),
                ('stem_choices', models.CharField(choices=[('6', '6'), ('40', '40'), ('40+', '40+')], default=6, max_length=1026)),
                ('revisions', models.CharField(choices=[('3', '3'), ('6', '6')], default=3, max_length=1026)),
                ('reference_link_type', models.CharField(blank=True, choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026, null=True)),
                ('reference_link', models.URLField(blank=True, null=True)),
                ('mix_extras', models.CharField(choices=[('Auto-Tune Lead Vocal', 'Auto-Tune Lead Vocal'), ('Auto-Tune Backing Vocals', 'Auto-Tune Backing Vocals'), ('Drum Replacement', 'Drum Replacement'), ('Instrumental Version', 'Instruemntal Version'), ('Show Ready Version', 'Show Ready Version'), ('A Capella Version', 'A Capella Version'), ('Group Mixed Stem Return', 'Group Mix Stem Return'), ('Individual Mixed Stem Return', 'Individual Mixed Stem Return')], default='', max_length=1026)),
                ('contact', models.EmailField(default='', max_length=254)),
                ('order_total', models.DecimalField(decimal_places=2, default=22.23, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Mixes',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='Production', max_length=15)),
                ('production_type', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('synths', 'Synths'), ('piano', 'Piano'), ('drums', 'Drums'), ('track_production', 'Track Production')], max_length=1026)),
                ('reference_link_type', models.CharField(choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026)),
                ('reference_link', models.URLField(blank=True)),
                ('deliver_by', models.DateField()),
                ('contact', models.EmailField(default='', max_length=254)),
                ('notes', models.CharField(max_length=320)),
            ],
        ),
    ]
