# Generated by Django 3.1.7 on 2021-03-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='reference_link_type',
            field=models.CharField(choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026, null=True),
        ),
    ]
