# Generated by Django 3.1.6 on 2021-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_master_mix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_by', models.DateField()),
                ('reference_link_type', models.CharField(choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], max_length=1026)),
                ('reference_link', models.URLField()),
                ('production_type', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('synths', 'Synths'), ('piano', 'Piano'), ('drums', 'Drums'), ('track_production', 'Track Production')], max_length=1026)),
            ],
        ),
    ]
