# Generated by Django 3.1.6 on 2021-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='order_type',
            field=models.CharField(default='Master', max_length=15),
        ),
        migrations.AddField(
            model_name='mix',
            name='order_type',
            field=models.CharField(default='Mix', max_length=15),
        ),
        migrations.AddField(
            model_name='production',
            name='order_type',
            field=models.CharField(default='Production', max_length=15),
        ),
    ]
