# Generated by Django 3.1.6 on 2021-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210311_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='package_type',
            field=models.CharField(choices=[('single (< 5mins)', 'single (< 5mins)'), ('ep (< 35mins)', 'ep (< 35mins)'), ('album / LP (> 35mins)', 'album / LP (> 35mins)')], default=[0], max_length=1026),
        ),
        migrations.AlterField(
            model_name='mix',
            name='revisions',
            field=models.CharField(choices=[('3', '3'), ('6', '6')], default=[0], max_length=1026),
        ),
        migrations.AlterField(
            model_name='mix',
            name='stem_choices',
            field=models.CharField(choices=[('6', '6'), ('40', '40'), ('40+', '40+')], default=[0], max_length=1026),
        ),
    ]
