# Generated by Django 3.1.6 on 2021-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210311_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='order_type',
            field=models.CharField(default='Production', max_length=15),
        ),
    ]
