# Generated by Django 3.1.6 on 2021-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210311_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='order_type',
            field=models.CharField(default='Master', max_length=15),
        ),
        migrations.AlterField(
            model_name='mix',
            name='order_type',
            field=models.CharField(default='Mix', max_length=15),
        ),
    ]
