# Generated by Django 3.1.6 on 2021-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20210319_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='reference_link_type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026),
        ),
        migrations.AlterField(
            model_name='mix',
            name='reference_link_type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026),
        ),
        migrations.AlterField(
            model_name='production',
            name='reference_link_type',
            field=models.CharField(choices=[('general', 'general'), ('energy', 'energy'), ('tone', 'tone'), ('instrument', 'instrument')], default='general', max_length=1026),
        ),
    ]
