# Generated by Django 3.1.6 on 2021-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20210319_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='mix_extras',
            field=models.CharField(blank=True, choices=[('Drum Replacement', 'Drum Replacement'), ('Instrumental Version', 'Instruemntal Version'), ('Show Ready Version', 'Show Ready Version'), ('A Capella Version', 'A Capella Version')], default='', max_length=1026),
        ),
        migrations.AlterField(
            model_name='mix',
            name='mix_extras',
            field=models.CharField(choices=[('Auto-Tune Lead Vocal', 'Auto-Tune Lead Vocal'), ('Auto-Tune Backing Vocals', 'Auto-Tune Backing Vocals'), ('Drum Replacement', 'Drum Replacement'), ('Instrumental Version', 'Instruemntal Version'), ('Show Ready Version', 'Show Ready Version'), ('A Capella Version', 'A Capella Version'), ('Group Mixed Stem Return', 'Group Mix Stem Return'), ('Individual Mixed Stem Return', 'Individual Mixed Stem Return')], default='', max_length=1026),
        ),
    ]
