# Generated by Django 3.1.6 on 2021-03-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20210320_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='mix',
            name='order_total',
        ),
    ]
