# Generated by Django 3.1.6 on 2021-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_mix_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
