# Generated by Django 3.1.6 on 2021-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20210320_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mix',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=22.23, max_digits=10),
        ),
    ]
