# Generated by Django 3.1.7 on 2021-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mix_extras',
            field=models.CharField(default='none', max_length=1026),
        ),
    ]
