# Generated by Django 3.1.6 on 2021-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_ordered',
            field=models.CharField(choices=[('MIX', 'Mix'), ('MASTER', 'Master')], default='MIX', max_length=6),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_ordered',
            field=models.CharField(choices=[('MIX', 'Mix'), ('MASTER', 'Master')], default='MIX', max_length=6),
        ),
    ]
