# Generated by Django 3.1.7 on 2021-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210323_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_link_type',
            field=models.CharField(blank=True, max_length=1026, null=True),
        ),
    ]
