# Generated by Django 3.1.6 on 2021-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='deliver_by',
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='mix_extras',
            field=models.CharField(default=1, max_length=1026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='reference_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_link_type',
            field=models.CharField(blank=True, max_length=1026),
        ),
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.CharField(default=3, max_length=1026),
        ),
        migrations.AddField(
            model_name='order',
            name='stem_choices',
            field=models.CharField(default=6, max_length=1026),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_ordered',
            field=models.CharField(default='MIX', max_length=6),
        ),
    ]
