# Generated by Django 3.1.6 on 2021-03-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210319_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_ordered',
            field=models.CharField(max_length=6),
        ),
    ]
