# Generated by Django 3.1.7 on 2021-03-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210327_2253'),
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('order_type', models.CharField(default='Production', max_length=20)),
                ('production_type', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('synths', 'Synths'), ('piano', 'Piano'), ('drums', 'Drums'), ('track_production', 'Track Production')], default='', max_length=50)),
                ('deliver_by', models.DateTimeField(auto_now_add=True)),
                ('reference_link_type', models.CharField(blank=True, max_length=1026, null=True)),
                ('reference_link', models.URLField(blank=True, null=True)),
                ('contact', models.EmailField(default='', max_length=254)),
                ('notes', models.CharField(max_length=1080)),
                ('original_bag', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_production', to='profiles.userprofile')),
            ],
        ),
    ]
