# Generated by Django 3.1.7 on 2021-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210330_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_by',
            field=models.DateField(),
        ),
    ]
